### ISSUE TITLE
environment.yml contains OSX specific dependencies

### ISSUE THREAD

**Issue by JakubPawlowskii** [Seb-Unit8/Unit8_Wroclaw_lectures#1]
I have tried to create the conda env, on a laptop running Pop!_OS 21.10, via cloning the repository and running `conda env create -f environment.yml`. I get the following output:

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - xz==5.2.5=haf1e3a3_1
  - clangxx==12.0.1=default_he082bbe_4
  - cctools_osx-64==973.0.1=h609b070_10
  - zeromq==4.3.4=he49afe7_1
  - openssl==3.0.3=hfe4f2af_0
  - clangxx_osx-64==12.0.1=hdb584c0_8
  - matplotlib-base==3.5.2=py310h4510841_0
  - libcurl==7.83.1=h23f1065_0
  - libwebp-base==1.2.2=h0d85af4_1
  - libdeflate==1.10=h0d85af4_0
  - fontconfig==2.14.0=h676cef8_0
  - cairo==1.16.0=h1680b09_1011
  - libsodium==1.0.18=hbcb3906_1
  - xorg-libxdmcp==1.1.3=h35c211d_0
  - expat==2.4.8=h96cf925_0
  - libzip==1.8.0=h7e5727d_1
  - atk-1.0==2.36.0=he69c4ee_4
  - libssh2==1.10.0=hd3787cc_2
  - readline==8.1=h05e3726_0
  - jpeg==9e=h5eb16cf_1
  - openjpeg==2.4.0=h6e7aa92_1
  - libxml2==2.9.14=h08a9926_0
  - libiconv==1.16=haf1e3a3_0
  - libblas==3.9.0=14_osx64_openblas
  - libnghttp2==1.47.0=hca56917_0
  - hdf5==1.12.1=nompi_h0aa1fa2_104
  - bzip2==1.0.8=h0d85af4_4
  - libwebp==1.2.2=h28dabe5_0
  - xorg-libxau==1.0.9=h35c211d_0
  - libgfortran5==9.3.0=h6c81a4c_23
  - graphviz==3.0.0=h6f567cf_1
  - ncurses==6.3=h96cf925_1
  - compiler-rt==12.0.1=he01351e_0
  - tapi==1100.0.11=h9ce4665_0
  - libbrotlidec==1.0.9=h5eb16cf_7
  - libgd==2.3.3=h1e214de_3
  - cctools==973.0.1=ha54d4a6_10
  - libffi==3.4.2=h0d85af4_5
  - curl==7.83.1=h23f1065_0
  - ld64_osx-64==609=hc6b1d1e_10
  - libcxx==14.0.3=hc203e6f_0
  - libxcb==1.13=h0d85af4_1004
  - ld64==609=h4dfd969_10
  - lz4-c==1.9.3=he49afe7_1
  - clang-12==12.0.1=default_he082bbe_4
  - libpng==1.6.37=h7cec526_2
  - icu==70.1=h96cf925_0
  - harfbuzz==4.2.1=h00bb2c2_0
  - pandoc==2.18=h694c41f_0
  - freetype==2.10.4=h4cff582_1
  - libclang-cpp12==12.0.1=default_he082bbe_4
  - lcms2==2.12=h577c468_0
  - gtk2==2.24.33=h7c1209e_2
  - zlib==1.2.11=h6c3fc93_1014
  - jupyter_core==4.10.0=py310h2ec42d9_0
  - libtool==2.4.6=he49afe7_1008
  - clang==12.0.1=h694c41f_4
  - libbrotlienc==1.0.9=h5eb16cf_7
  - libbrotlicommon==1.0.9=h5eb16cf_7
  - pixman==0.40.0=hbcb3906_0
  - brotli==1.0.9=h5eb16cf_7
  - zstd==1.5.2=h582d3a0_0
  - jbig==2.1=h0d85af4_2003
  - libzlib==1.2.11=h6c3fc93_1014
  - libopenblas==0.3.20=openmp_hb3cd9ec_0
  - libtiff==4.3.0=h17f2ce3_3
  - libllvm12==12.0.1=hd011deb_2
  - clang_osx-64==12.0.1=h633439f_8
  - lerc==3.0=he49afe7_0
  - llvm-tools==12.0.1=hd011deb_2
  - libgfortran==5.0.0=9_3_0_h6c81a4c_23
  - ca-certificates==2021.10.8=h033912b_0
  - gts==0.7.6=hccb3bdf_2
  - graphite2==1.3.13=h2e338ed_1001
  - pcre==8.45=he49afe7_0
  - python==3.10.4=h1cc4136_0_cpython
  - libev==4.33=haf1e3a3_1
  - llvm-openmp==14.0.3=ha654fa7_0
  - brotli-bin==1.0.9=h5eb16cf_7
  - libedit==3.1.20191231=h0678c8f_2
  - c-ares==1.18.1=h0d85af4_0
  - krb5==1.19.3=hb98e516_0
  - libnetcdf==4.8.1=nompi_h6609ca0_102
  - cxx-compiler==1.4.1=hbb4e6a2_0
  - fribidi==1.0.10=hbcb3906_0
  - c-compiler==1.4.1=h774085c_0
  - librsvg==2.54.1=h3d48ba6_0
  - libcblas==3.9.0=14_osx64_openblas
  - pip==22.1=pyhd8ed1ab_0
  - liblapack==3.9.0=14_osx64_openblas
  - pango==1.50.7=hc4a7b6d_0
  - tk==8.6.12=h5dbffcc_0
  - sqlite==3.38.5=hd9f0692_0
  - giflib==5.2.1=hbcb3906_2
  - gettext==0.19.8.1=hd1a6beb_1008
  - libglib==2.70.2=hf1fb8c0_4
  - pthread-stubs==0.4=hc929b4f_1001
  - hdf4==4.2.15=hefd3b78_3
  - gdk-pixbuf==2.42.8=hb161b9c_0
  - sigtool==0.1.3=h88f4db0_0

It seems that some of these packages' versions are specific for OSX.
Perhaps it's possible to restrict the .yml file to the bare minimum and let conda handle the rest.

**Comment by Seb-Unit8** [comment]
Thanks for the catch @JakubPawlowskii, seems that in trying to lock in a config I knew worked I over engineered it (and my tester had a mac!).

#2 Should fix this, if you could please give that a test on your system and confirm if the env builds that would be stellar.

**Comment by JakubPawlowskii** [comment]
Env from #2 builds correctly. However, I had to install jupyter-lab separately as it was not included.  I managed to run two notebooks from lecture_1 folder.
